### ISSUE TITLE
Please verify SteamVR is properly installed and try again

### ISSUE THREAD

**Issue by organnerx** [KonqiTheKonqueror/Source2-PFSK#5]
I have this error even though I followed a tutorial. Argument "-novr" is not helping to fix this startup problem.
Do I need to install SteamVR software to play the game without VR? This wasn't specified in mod tutorial.
I thought the goal of this project was to remove dependence from VR software. Maybe I'm wrong.

**Comment by KonqiTheKonqueror** [comment]
Hello, unfortunately, this is not an issue with the Pancake FPS Starter Kit, but rather an issue with your game installation, which I cannot assist you with outside of extremely basic troubleshooting tips.

Try right clicking Half-Life: Alyx in your steam library, clicking on "Properties", select "DLC", and check "INSTALL" under "Half-Life: Alyx - Workshop Tools". If this does not work, please contact Steam Support with the following link: https://help.steampowered.com/en/wizard/HelpWithGame/?appid=546560
