### ISSUE TITLE
 game dosen't start

### ISSUE THREAD

**Issue by abacus12345** [KonqiTheKonqueror/Source2-PFSK#7]
So, I installed the Pancake Mod for HL: Alyx along with the crowbar fix and I had overwritten the files. But when I tried to start it, the game closes.

Can someone help?

- Cirk K.

**Comment by KonqiTheKonqueror** [comment]
Hello,

This does not appear to be an issue with the Pancake FPS Starter Kit, but rather something else in the line of software you're using. Unfortunately, I can only assist you with issues with the Pancake FPS Starter Kit, not Half-Life: Alyx.

Please contact Steam Support for further assistance through the following link: https://help.steampowered.com/en/wizard/HelpWithGame/?appid=546560

Make sure you include in your report that the game crashes on startup.
